# Application
spring.application.name=chinook-jpa-entity-generator

# PostgreSQL Chinook Database
spring.datasource.url=jdbc:postgresql://localhost:5432/chinook
spring.datasource.username=postgres
spring.datasource.password=root

# PostgreSQL JDBC Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# Logging
logging.level.root=INFO
logging.level.edu=DEBUG